name: Ping Cloudflare Scanner

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:
  repositor

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Scanner
        run: |
          curl -s -H "Authorization: ${{ secrets.SECRET_KEY }}" "${{ secrets.SCANNER_URL }}"
